import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

export const YAML_HOST_REL = path.join(".convoy", "yaml-host.e2e.ts");

const HOST_SOURCE = `// Generated by convoy run — host file so YAML tests can load. Do not edit.
export {};
`;

export function yamlHostPath(cwd: string): string {
  return path.join(cwd, YAML_HOST_REL);
}

/** Vitest will not collect tests from setupFiles alone; yaml-only runs need a host file in the project. */
export function ensureYamlHost(cwd: string): string {
  const host = yamlHostPath(cwd);
  mkdirSync(path.dirname(host), { recursive: true });
  writeFileSync(host, HOST_SOURCE, "utf8");
  return host;
}

export function removeYamlHost(cwd: string): void {
  const host = yamlHostPath(cwd);
  if (existsSync(host)) rmSync(host);
}
